modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dungeons_gear"
version="${file.jarVersion}"
displayName="Dungeons Gear"
authors="Userofbricks, the_infamous_1"

[[dependencies.dungeon_gear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




